### PR TITLE
Release/v3.0

### PR DESCRIPTION
**Pull request by jaydrogers**
### ⚠️ This PR is a work in progress
I will continue to update this comment as I expand more.

### 👀 Preview the new site
This PR automatically builds a new preview site:
- https://release-v3-0.docker-php.pages.dev/

## What this PR does
This PR has a major improvements and changes. **It is a foundational shift in the direction of this project (all for the good).** Migration guides and a plethora of documentation will be created to help you migrate.

## Background
The "Docker PHP" project has been around for a number of years, providing an awesome user experience for PHP sysadmins. It has always been based off of Ubuntu images and used the Ondrej PPA for getting PHP modules/extensions.

In version 2.0, we embraced the use of S6 overlay -- which worked great for solving the problem of running multiple services in a single container (especially for things like NGINX + FPM),

## Problem
These images have really started to build up in popularity and more advanced use cases are coming in.

A major few problems have come up:
- S6 Overlay is not fully compatible with all hosts and [there wasn't really a way around it](https://github.com/just-containers/s6-overlay/issues/535#issuecomment-1597680218)
- There is not a way to pin a minor version for PHP (Example: 8.2.11) with Ondrej PHP ([read more](https://github.com/oerdnj/deb.sury.org/discussions/2014))

## Proposed solution
These two problems turned into a massive perspective change since these two restrictions greatly inhibit the stability, compatibility, and precision of these images.

### Change the source of PHP from "ppa:ondrej/php" to the Official PHP Docker Images
image
Since version pinning is not possible with APT, we decided the best place to get PHP is from PHP themselves. For the 3.0 release, we will be taking our lovely developer experience and bringing this to you on images that are based directly from the official PHP Docker images -- with a bunch of improvements.

**Major benefits:**
- We can reduce our reliance on S6 Overlay (S6 will only be used in our `fpm-nginx` and `fpm-apache` variations
- We can pull in specifically what minor version we want to work with
- People who are using the official PHP images already will be able to confidently switch by a simple image name change
- We will be able to offer an Alpine version of the images (a much smaller footprint compared to other OS distros)

**Breaking changes:**
Because of this change, our current users will need to be aware of a few major breaking changes:
- Ubuntu will no longer be offered. Everything from PHP is Debian or Alpine only.
- PHP Extensions will need to be installed via PECL (ie. `apt install php-redis` won't work anymore). We will provide wonderful documentation and content on how you can add do this

**Things that will not change:**
- We will continue to provide a beautiful sysadmin & development experience

**New features:**
- For every PHP version, we will offer a `debian` and `alpine` version
- Users can easily customize their container start up behavior by dropping scripts into `/etc/entrypoint.d/` (this experience is DOPE and we will document it soon)
- You can select which PHP version you want by major, minor, or patch (ex. `8`, `8.2`, `8.2.11`)
- We will be offering an `nginx-unit` variation (we're really hoping this will be the ultimate way to run modern PHP)

## Documentation improvements
As we work on this release, we intend to create a lot of content to show you more of behind the scenes and give you more practical examples of running these images in development, CI, and production.

@danpastori and I will be working on building [Financial Freedom](https://github.com/serversideup/financial-freedom) in public, an open source alternative to Mint/YNAB that is based off of Laravel and can be run in the cloud or people's  homelabs. Expect more content to appear on our YouTube channel, Twitter, and more.

While things are still in progress, I will also pick some special use cases and create videos on how to extend the new type of images that we are creating. Below is a list of things to add to the documentation (feel free to comment below if you have more suggestions)

#### Related Discussions:
- https://github.com/serversideup/docker-php/discussions/167
- https://github.com/serversideup/docker-php/discussions/206
- https://github.com/serversideup/docker-php/discussions/173
- https://github.com/serversideup/docker-php/discussions/200
- https://github.com/serversideup/docker-php/discussions/191

## Special Note
```txt
👉 This PR is a work in progress and any updates will be added to this top message
```

### CODE REVIEW

**Comment by spyridonas** [comment]
Do you think that it's possible to include https://github.com/mlocati/docker-php-extension-installer on your images for easier dependency installation ? It will also cleanup all the dev dependencies after the php addon is done compiling.

**Comment by jaydrogers** [comment]
Hey @spyridonas,

I have these very simple bin scripts that will help. If the project needs something more robust, I will definitely consider it

https://github.com/serversideup/docker-php/tree/release/v3.0/src/common/usr/local/bin

**Comment by okaufmann** [comment]
Hi @jaydrogers, I am utilizing the `serversideup/php` image to orchestrate a Laravel application across three distinct containers:

- **Webapp Container**: Hosts nginx and PHP-FPM, exposing a designated port for application accessibility.
- **Queue Container**: Dedicated to running Horizon.
- **Scheduler Container**: Executes the `php artisan schedule:work` command.

This architecture facilitates individual scaling of each component on Kubernetes.

However, I've observed that nginx and PHP-FPM are initialized in every container, which significantly increases the RAM usage, especially when managing numerous Laravel instances.

To mitigate this, I've resorted to creating two unique images:
1. A webapp image derived from `serversideup/php:8.2-fpm-nginx`.
2. A shared image for the queue and scheduler containers based on `serversideup/php:8.2-cli`.

This workaround, albeit functional, introduces a complex initial build configuration and heightens the potential for failure due to the need to manage multiple images.

In the past, I've employed a container role concept. Despite the image having the capability to host the webapp, assigning a role like `queue` via environment variable prevented the initialization of nginx and PHP-FPM, thereby optimizing RAM utilization.

I am inquiring if a similar container role feature could be envisaged for future releases, to streamline resource utilization, reduce RAM usage, and simplify image management.

**Comment by jaydrogers** [comment]
@okaufmann: Your question belongs in our "Q&A" under Discussions and should be opened there: https://github.com/serversideup/docker-php/discussions/categories/q-a

**Comment by smujaddid** [comment]
I noticed both cli and fpm Dockerfile got swapped, at least their declared PHP_VARIATION

**Comment by jaydrogers** [comment]
Thanks @smujaddid! Fixed in https://github.com/serversideup/docker-php/pull/207/commits/7cc51fde19e9c21ad79ad42d4f6e4ce1452d94b2

**Comment by ankurk91** [comment]
I would still want you guys to include recommend php extensions installed by default.

**Comment by jaydrogers** [comment]
> I would still want you guys to include recommend php extensions installed by default.

I spoke to a few people about this. It's hard to predict what people will need (especially things like Redis, not every project as that).

For the initial release of the beta, I will keep things as "official PHP" as possible when it comes to extensions, but I am writing tools to make it easier to install (https://github.com/serversideup/docker-php/blob/release/v3.0/src/common/usr/local/bin/docker-php-serversideup-pecl-install).

I will also be documenting the crap out of this release to make it easy for people to get started and how to customize it their way.

**Comment by ijpatricio** [comment]
1. Yes.
2. Yes.
3. Yes 👍 But, like everything in life, there will be different scenarios.

It's simple to turn off all defaults, I can see.
And adding a bash file for execution?

Like "my-startup.sh" in the root project?
Having it chmod for execution and ran?

Or having a `server-side-up-startup.yml` file where I can write commands?

**Comment by jaydrogers** [comment]
> And adding a bash file for execution?
> 
> Like "my-startup.sh" in the root project? Having it chmod for execution and ran?

Adding your own scripts is possible, but documenting this week. It's something different then our own automation script. You'll be excited when you see how this works! Stay tuned 😃

**Comment by a-h-abid** [comment]
Just a suggestion...

For PHP Extensions installation, can you integrate with this tool https://github.com/mlocati/docker-php-extension-installer ... or you make something similar ? I like this tool for the very easy extensions install process.

**Comment by jaydrogers** [comment]
@a-h-abid: Already done in the beta release 😎

https://release-v3-0.docker-php.pages.dev/docs/guide/installing-additional-php-extensions

**Comment by pbromb** [comment]
Hi @jaydrogers, in the Nginx Unit version, opcache is installed but not enabled. If someone notices it, they may experience performance issues. 
It would be nice if the 10-init-unit.sh script allowed installing a custom config.json file as well.
Very good changes in the v3 version

**Comment by bensherred** [comment]
Hey @jaydrogers, amazing work on this so far, and really looking forward to the stable release. I've been using these beta versions for a side project and I've noticed that the `fpm-nginx` image doesn't appear to be copying/executing custom entrypoint scripts.

From what I can tell, the `src/variations/fpm-nginx/Dockerfile` doesn't appear to be calling `ENTRYPOINT ["docker-php-serversideup-entrypoint"]` unlike the others? Is there a reason behind this?

**Pull request merged**
