### PR TITLE
Configure permissions on /run directory for compatibility with cloud providers

### PR DESCRIPTION
**Pull request by jaydrogers**
## What this PR does
- Fixes permissions issues for running with Azure and Google Cloud Run
- Fixes some CI/CD stuff for PRs

## Related Discussions
- https://github.com/serversideup/docker-php/pull/376#issuecomment-2179262427)

### Co-authored by
- @hajekj

### CODE REVIEW

**Comment by jaydrogers** [comment]
@hajekj: I have the images publishing now under my own branch. This should fix all the non-sense with GitHub Actions.

These tags will be prefixed with the PR number now.

**Example:**
```
docker.io/serversideup/php-dev:385-7.4.33-cli-alpine  
docker.io/serversideup/php-dev:385-7.4-cli-alpine  
docker.io/serversideup/php-dev:385-7.4-alpine  
docker.io/serversideup/php-dev:385-7-cli-alpine  
docker.io/serversideup/php-dev:385-7-alpine  
```

Once this is done, if you can confirm the changes are there and work that would be great.

I would test the following Operating System variations to be sure this works across the board:
- Alpine
- Bookworm
- Bullseye

### If this does not work
We can do the `chown -R 755` as you initially proposed. I am just trying to take the "least privilege" route.

Thanks for your patience and dedication on this issue!

**Comment by hajekj** [comment]
That did the job - http://container-apps-test--jafwdzh.purplemoss-bcf270ea.westeurope.azurecontainerapps.io/

The image is now running in Azure just fine.

**Comment by jaydrogers** [comment]
Sweet! Thanks for the update!

Did it work on the other operating systems too?

**Comment by hajekj** [comment]
The builds are now complete, so managed to test all of those you listed.

**Comment by jaydrogers** [comment]
Thanks a ton for your help @hajekj!

I have this merged and it will be released soon.

I might do a beta release with this one then merge it to stable later on.

**Pull request merged**
