### PR TITLE
Add PHP 8.4 support

### PR DESCRIPTION
**Pull request by tomschlick**
Attempted to do the initial setup for PHP 8.4 support here. 

The official images at [docker.io/library/php ](https://hub.docker.com/_/php/tags?name=8.4) haven't been built yet so we will have to wait for those to fully test and merge. Keeping this as draft until then.

### CODE REVIEW

**Comment by tomschlick** [comment]
Official Base Image PR for tracking: https://github.com/docker-library/php/pull/1548

**Comment by jaydrogers** [comment]
It's been merged, now we just have to keep an eye on this https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/

**Comment by tomschlick** [comment]
Tags are now on dockerhub! https://hub.docker.com/_/php/tags?name=8.4.1

**Comment by jaydrogers** [comment]
We still have to wait 😃

The images are published, but they don't have any actual images pushed.

### 8.4 images without architectures
image

### Older 8.3 images with different architectures
image

**Comment by tomschlick** [comment]
Yeah just noticed all the failures. Looks like that Jenkins project is marked as disabled. Not sure if they are still using that or moved to something else.

**Comment by jaydrogers** [comment]
I wonder if they have it manually disabled until they are ready to run?

Usually that's what they've used in the past. It's still linked from their README, so I will just kind of keep an eye on it.

In my experience, it takes quite some time for the images to build. Keep me posted if you see anything else in the meantime.

Thanks for all your help!

**Comment by jaydrogers** [comment]
8.1.31 (a new patch version for 8.1) is killing the process 🙃

I think we're gonna just have to try again tomorrow. The AMD64 architecture is appearing for some, but they are missing the ARM64 architecture.

image

**Comment by tomschlick** [comment]
Sooo close, yet so far away 😢

**Comment by tomschlick** [comment]
arm64/v8 now showing so hopefully this next build should work 🤞 

https://hub.docker.com/layers/library/php/8.1.31-fpm-alpine/images/sha256-7be75c7cf9fcecd5f1672fde362588e4d25e987879553dcf33d283fa1d99ce0c?context=explore

**Comment by jaydrogers** [comment]
Woohoo!

CI passed, so I merged it and I am running a beta release now 😅🤞

https://github.com/serversideup/docker-php/actions/runs/11966269031

If that passes, I will push these to stable tomorrow 👍

**Pull request merged**
